// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nprdhthsgqfwhibgvcml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wcmRodGhzZ3Fmd2hpYmd2Y21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDAyNjEsImV4cCI6MjA2MTAxNjI2MX0.RBusXzwElvsOSBpgyG5qb52JAprYjsQrYVmlgXnfr_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);