// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twouhmjqotgpmiyxlbuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3b3VobWpxb3RncG1peXhsYnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTc3NjcsImV4cCI6MjA2MDk3Mzc2N30.uowrsHtMmGd_JfuiHDshekXtE4qJa1UNwrZn__m7cXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);